name: Deploy to Google Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Debug to check if the secret is injected (optional, remove after success)
      - name: Debug Secret
        run: echo "GCP_SA_KEY content: ${{ secrets.GCP_SA_KEY }}"

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Configure Docker to use gcloud for Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-player/demo-app:$GITHUB_SHA .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-player/demo-app:$GITHUB_SHA

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy music-player-service \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-player/demo-app:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet