name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Configure Docker for Google Cloud
      - name: Configure Docker
        run: gcloud auth configure-docker gcr.io --quiet

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/music-player-456405/reactbuilds/musicplayer:latest .
          docker push gcr.io/music-player-456405/reactbuilds/musicplayer:latest

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image gcr.io/music-player-456405/reactbuilds/musicplayer:latest \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --port 8080 \
            --allow-unauthenticated \
            --quiet